#1부터 10까지(미포함)의 2걸음 크기의 정수값 배열을 생성해보자

In [5]:
import numpy as np
arr=np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


#모양이 (3, 4)인 모든 값이 1인 배열을 생성해보자

In [2]:
import numpy as np
arr=np.ones((3, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#0과 1 사이를 10등분하고자 할 때 등분값 배열을 생성해보자

In [3]:
import numpy as np
arr=np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [30]:
#A행렬을 생성해보자
import numpy as np
A = np.array([[ 1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
#A의 모양을 출력해보자
print('shape=', A.shape)
#19값을 출력해보자
print(A[3, 3])
#슬라이싱을 이용하여 [[1, 2], [6, 7]]값을 추출해보자
print(A[0:2, 0:2])
#슬라이싱을 이용하여[[19, 20], [24, 25]]값을 추출해보자
print(A[3:5, 3:5])
#슬라이싱을 이용하여 0축의 첫 번째 행과 두 번째 행을 추출해보자
print(A[])
#슬라이싱을 이용하여 1축의 마지막 열과 마지막 직전 열을 추출해보자
print(A[])

shape= (5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[16 17 18 19 20]
 [21 22 23 24 25]]


In [36]:
import numpy as np
A=np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]], [[25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]]])
#모양과 크기 출력
print(A.shape, A.size)
#(3, 4, 3)으로 모양 변경
B=A.reshape(3, 4, 3)
print(B)
#1차원으로 변경
C=A.flatten()
print(C)

(3, 3, 4) 36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
